---
version: '0.2'
phases:
    pre_build:
        commands:
            - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8) # noqa
            - export IMAGE_TAG=$COMMIT_HASH
            - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI # noqa
    build:
        commands:
            - docker build -t $ECR_REPO_URI:latest .
            - docker tag $ECR_REPO_URI:latest $ECR_REPO_URI:$IMAGE_TAG # noqa
    post_build:
        commands:
            - aws ssm put-parameter --name /nginx/image-tag --value $IMAGE_TAG --type String --overwrite # noqa
            - docker push $ECR_REPO_URI:$IMAGE_TAG
            - docker push $ECR_REPO_URI:latest
            - echo $IMAGE_TAG > image-tag.txt
artifacts:
    files:
        - image-tag.txt
