---
account_number: 123459992324
region: us-east-1
repository:
    owner: minhngocfree
    name: aws-java
ec2_properties:
    instance_type: t3.medium
scaling_policy:
    target_cpu_utilization: 60
    scale_in_cooldown: 300
    scale_out_cooldown: 300
    min_capacity: 4
    max_capacity: 8
